"""SQLAlchemy models.

Phase 0 scope: reference data, the transaction ledger, opening balances and budgets --
everything the reconciliation gate needs. The feature-module tables (projection, payslip,
card, cycling) arrive with their phases; adding tables to SQLite later is free, it is
altering existing ones that hurts.

Money is stored as INTEGER pence via the Money type below. SQLite has no decimal type, so
a REAL column would reintroduce exactly the float artefacts the workbook already suffers
from (1530.0000000000146). Integers keep SUM() exact, which matters because every balance
in this application is a sum.
"""

from __future__ import annotations

import datetime as dt
from decimal import Decimal, ROUND_HALF_UP

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    TypeDecorator,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

PENCE = Decimal("0.01")


class Money(TypeDecorator):
    """Decimal pounds in Python, integer pence in the database."""

    impl = Integer
    cache_ok = True

    def process_bind_param(self, value, dialect):
        if value is None:
            return None
        return int(Decimal(str(value)).quantize(PENCE, rounding=ROUND_HALF_UP) * 100)

    def process_result_value(self, value, dialect):
        if value is None:
            return None
        return (Decimal(value) / 100).quantize(PENCE)


class Base(DeclarativeBase):
    pass


# A random 16-byte hex string, generated by SQLite so it applies to rows inserted by any
# route. This is the sync identity for cross-machine merges (DESIGN.md 6.3.3); the integer
# primary key stays for joins and readability.
_UID_DEFAULT = text("lower(hex(randomblob(16)))")


def _uid_column() -> Mapped[str]:
    return mapped_column(String(32), unique=True, nullable=False, server_default=_UID_DEFAULT)


# --------------------------------------------------------------------------- reference


class Account(Base):
    __tablename__ = "account"

    id: Mapped[int] = mapped_column(primary_key=True)
    uid: Mapped[str] = _uid_column()
    name: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    short_code: Mapped[str] = mapped_column(String(16), unique=True, nullable=False)
    # 'bank' or 'credit_card'. Determines posting sign: a credit card balance is positive
    # debt, so a debit increases it. Derived from the month-tab row-4 formula on import.
    type: Mapped[str] = mapped_column(String(16), nullable=False)

    is_savings: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    savings_limit: Mapped[Decimal | None] = mapped_column(Money)
    is_investment: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    investment_limit: Mapped[Decimal | None] = mapped_column(Money)
    is_isa: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    # Earmarked pots -- money that is nominally saved but already spoken for. The Summary
    # tab's 'Less SC & Wed' column subtracted these by hand; flagging the accounts means the
    # column follows when a pot is added, which the workbook's header did not (Tembo joined
    # in June and the label was never updated).
    exclude_from_savings: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False
    )

    # Credit cards only: the day the statement is issued and the day the direct debit is
    # taken. Month-tab rows 48 and 50, which held them per month even though they never
    # varied by month.
    statement_day: Mapped[int | None] = mapped_column(Integer)
    payment_day: Mapped[int | None] = mapped_column(Integer)

    display_order: Mapped[int | None] = mapped_column(Integer)
    # Effective dating replaces the twelve per-month offset columns in Selections!Z:AK and
    # removes the need for update_months entirely (DESIGN.md 3.2).
    valid_from: Mapped[dt.date] = mapped_column(Date, nullable=False)
    valid_to: Mapped[dt.date | None] = mapped_column(Date)

    __table_args__ = (
        CheckConstraint("type IN ('bank','credit_card')", name="ck_account_type"),
    )

    def __repr__(self) -> str:
        return f"<Account {self.name!r} {self.type}>"


class Classification(Base):
    """Bills, Food, Excess, Savings ... -- the workbook's 'Purchase type'."""

    __tablename__ = "classification"

    id: Mapped[int] = mapped_column(primary_key=True)
    uid: Mapped[str] = _uid_column()
    name: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    legacy_ref: Mapped[int] = mapped_column(Integer, nullable=False)  # Selections!I
    direction: Mapped[int] = mapped_column(Integer, nullable=False)  # Selections!J, +1/-1
    rollover: Mapped[str] = mapped_column(String(16), nullable=False, default="none")
    counts_as_spend: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    display_order: Mapped[int | None] = mapped_column(Integer)
    valid_from: Mapped[dt.date] = mapped_column(Date, nullable=False)
    valid_to: Mapped[dt.date | None] = mapped_column(Date)

    # 'credit' / 'debit' rather than the workbook's 'positive' / 'negative': the rule is
    # about which kind of balance carries forward, which is clearer said that way round.
    __table_args__ = (
        CheckConstraint(
            "rollover IN ('none','all','credit','debit')", name="ck_classification_rollover"
        ),
    )

    def __repr__(self) -> str:
        return f"<Classification {self.name!r}>"


class Category(Base):
    """Mortgage, Going Out, Electricity ... -- the workbook's 'Category'."""

    __tablename__ = "category"

    id: Mapped[int] = mapped_column(primary_key=True)
    uid: Mapped[str] = _uid_column()
    name: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    grouping: Mapped[str] = mapped_column(String(32), nullable=False)  # Selections!AM
    spend_type: Mapped[str] = mapped_column(String(16), nullable=False)  # Selections!AO
    display_order: Mapped[int | None] = mapped_column(Integer)
    valid_from: Mapped[dt.date] = mapped_column(Date, nullable=False)
    valid_to: Mapped[dt.date | None] = mapped_column(Date)

    __table_args__ = (
        CheckConstraint("spend_type IN ('Credit','Debit','All')", name="ck_category_spend_type"),
    )

    def __repr__(self) -> str:
        return f"<Category {self.name!r}>"


# ------------------------------------------------------------------------------ ledger


class ImportBatch(Base):
    __tablename__ = "import_batch"

    id: Mapped[int] = mapped_column(primary_key=True)
    uid: Mapped[str] = _uid_column()
    created_at: Mapped[dt.datetime] = mapped_column(DateTime, server_default=func.now())
    filename: Mapped[str | None] = mapped_column(Text)
    row_count: Mapped[int | None] = mapped_column(Integer)
    note: Mapped[str | None] = mapped_column(Text)

    transactions: Mapped[list["Txn"]] = relationship(back_populates="batch")


class Txn(Base):
    """One user-entered transaction. Transfers are a single row with both accounts set;
    postings() explodes them into signed per-account movements."""

    __tablename__ = "txn"

    id: Mapped[int] = mapped_column(primary_key=True)
    uid: Mapped[str] = _uid_column()

    txn_date: Mapped[dt.date] = mapped_column(Date, nullable=False, index=True)
    period: Mapped[str] = mapped_column(String(7), nullable=False, index=True)  # 'YYYY-MM'
    type: Mapped[str] = mapped_column(String(16), nullable=False)
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False)

    account_from_id: Mapped[int] = mapped_column(ForeignKey("account.id"), nullable=False)
    account_to_id: Mapped[int | None] = mapped_column(ForeignKey("account.id"))
    category_id: Mapped[int | None] = mapped_column(ForeignKey("category.id"))
    classification_id: Mapped[int | None] = mapped_column(ForeignKey("classification.id"))

    comment: Mapped[str | None] = mapped_column(Text)
    category_comment: Mapped[str | None] = mapped_column(Text)
    # The workbook's natural key (e.g. '0401_BAAM_0'). Useful for de-duplicating re-imports
    # and for flagging near-duplicates during a cross-machine merge (DESIGN.md 6.3.4).
    legacy_identifier: Mapped[str | None] = mapped_column(String(64), index=True)

    created_at: Mapped[dt.datetime] = mapped_column(DateTime, server_default=func.now())
    deleted_at: Mapped[dt.datetime | None] = mapped_column(DateTime)
    deleted_reason: Mapped[str | None] = mapped_column(Text)
    source: Mapped[str] = mapped_column(String(16), nullable=False, default="manual")
    batch_id: Mapped[int | None] = mapped_column(ForeignKey("import_batch.id"))

    batch: Mapped[ImportBatch | None] = relationship(back_populates="transactions")
    account_from: Mapped[Account] = relationship(foreign_keys=[account_from_id])
    account_to: Mapped[Account | None] = relationship(foreign_keys=[account_to_id])
    category: Mapped[Category | None] = relationship()
    classification: Mapped[Classification | None] = relationship()

    __table_args__ = (
        CheckConstraint("type IN ('Credit','Debit','Transfer')", name="ck_txn_type"),
        CheckConstraint("amount >= 0", name="ck_txn_amount_non_negative"),
        # A transfer needs a destination; anything else must not have one.
        CheckConstraint(
            "(type = 'Transfer') = (account_to_id IS NOT NULL)", name="ck_txn_transfer_has_to"
        ),
    )

    def __repr__(self) -> str:
        return f"<Txn {self.txn_date} {self.type} {self.amount}>"


# ------------------------------------------------------------------- periodic reference


class OpeningBalance(Base):
    """Month-tab row 60 ('Start') per account."""

    __tablename__ = "opening_balance"

    account_id: Mapped[int] = mapped_column(ForeignKey("account.id"), primary_key=True)
    period: Mapped[str] = mapped_column(String(7), primary_key=True)
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False)


class Budget(Base):
    """Month-tab columns C and D: Income and Expected Costs, per category."""

    __tablename__ = "budget"

    period: Mapped[str] = mapped_column(String(7), primary_key=True)
    category_id: Mapped[int] = mapped_column(ForeignKey("category.id"), primary_key=True)
    income: Mapped[Decimal | None] = mapped_column(Money)
    expected: Mapped[Decimal | None] = mapped_column(Money)


class Projection(Base):
    """Projected Costs E8:K39 -- expected spend per day, per classification.

    The workbook held one month at a time and the month tabs read it through xlProj<Class>
    for any date after today. Keyed by date here, so several months can coexist.
    """

    __tablename__ = "projection"

    proj_date: Mapped[dt.date] = mapped_column(Date, primary_key=True)
    classification_id: Mapped[int] = mapped_column(
        ForeignKey("classification.id"), primary_key=True
    )
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False, default=Decimal("0"))
    comment: Mapped[str | None] = mapped_column(Text)


class ClassificationOpening(Base):
    """Opening balance for a classification's running total.

    April's Running Excess formula ends in a bare '-2632.45' -- the balance carried in from
    the previous year's workbook, typed into the formula because there was nowhere to store
    it. Here it has a home, so the year can start from a stated figure rather than a
    literal buried in a cell.
    """

    __tablename__ = "classification_opening"

    period: Mapped[str] = mapped_column(String(7), primary_key=True)
    classification_id: Mapped[int] = mapped_column(
        ForeignKey("classification.id"), primary_key=True
    )
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False)


class ClassificationAllowance(Base):
    """Month-tab C54, 'Spend per day'.

    Running Excess gains this every day of the month, on top of actual spend. The workbook
    applied it by testing whether the column header ended in 'Excess'; keying it properly
    means any classification can carry an allowance, and it can differ by month -- which it
    does, being absent before July and 30 from July onwards.
    """

    __tablename__ = "classification_allowance"

    period: Mapped[str] = mapped_column(String(7), primary_key=True)
    classification_id: Mapped[int] = mapped_column(
        ForeignKey("classification.id"), primary_key=True
    )
    daily_amount: Mapped[Decimal] = mapped_column(Money, nullable=False)


class Payslip(Base):
    """Salary tracker, actual side (columns B:M)."""

    __tablename__ = "payslip"

    period: Mapped[str] = mapped_column(String(7), primary_key=True)
    payday: Mapped[int | None] = mapped_column(Integer)
    gross: Mapped[Decimal | None] = mapped_column(Money)
    ni: Mapped[Decimal | None] = mapped_column(Money)
    holiday_pay: Mapped[Decimal | None] = mapped_column(Money)
    cycle_to_work: Mapped[Decimal | None] = mapped_column(Money)
    paye: Mapped[Decimal | None] = mapped_column(Money)
    net: Mapped[Decimal | None] = mapped_column(Money)
    # Expected side (columns O:W): the inputs the model needs, not its outputs.
    salary: Mapped[Decimal | None] = mapped_column(Money)  # O, annual
    # P, and *not* salary/12: a bonus month carries its own figure, which is why May's
    # expected gross is 39,724 against an annual salary of 128,350.
    expected_gross: Mapped[Decimal | None] = mapped_column(Money)
    benefits: Mapped[Decimal | None] = mapped_column(Money)
    additional: Mapped[Decimal | None] = mapped_column(Money)


class SalaryAssumption(Base):
    """The PAYE/NI bands from Salary tracker C18:F36, as monthly figures.

    Effective-dated because the personal allowance is tapered in four steps across the year
    (PA - 1 through PA - 4, each with its own start date in F24:F27).

    Rates are stored as percentages, not fractions: 8% is 8.00, not 0.08. The Money column
    holds two decimal places, so a fraction could only express whole percentage points --
    fine for 20% and 45%, useless for an 8.5% NI rate. As percentages the same column
    resolves to a hundredth of a point.
    """

    __tablename__ = "salary_assumption"

    tax_year: Mapped[int] = mapped_column(Integer, primary_key=True)
    key: Mapped[str] = mapped_column(String(48), primary_key=True)
    effective_from: Mapped[dt.date] = mapped_column(Date, primary_key=True)
    value: Mapped[Decimal] = mapped_column(Money, nullable=False)


class SalaryProfile(Base):
    """Annual salary, effective-dated -- the input behind 'Gross pay (expected)'.

    The workbook typed the annual figure into every one of the twelve rows of column O, so a
    pay rise meant editing each month from that point on and hoping none were missed. One
    row per change here; the month picks up whichever is in force.
    """

    __tablename__ = "salary_profile"

    id: Mapped[int] = mapped_column(primary_key=True)
    uid: Mapped[str] = _uid_column()
    effective_from: Mapped[dt.date] = mapped_column(Date, unique=True, nullable=False)
    annual_salary: Mapped[Decimal] = mapped_column(Money, nullable=False)
    note: Mapped[str | None] = mapped_column(Text)


class Bonus(Base):
    """A one-off payment on top of salary/12, by the month it is paid.

    May's expected gross was `ROUND(O5/12,2)+29028.48` -- the bonus welded into the formula,
    which is why expected gross could not simply be derived. Held as data, the derivation
    works again: expected gross = salary in force / 12 + any bonus for the month.

    The actual columns are here rather than on `payslip` because a bonus is frequently paid
    on its own day, as its own payment with its own deductions. `payslip` is keyed by period,
    so recording the bonus there would have overwritten the month's salary -- two payments in
    one month is exactly the case a single row per month cannot hold. The Salary page adds
    the two together.
    """

    __tablename__ = "bonus"

    period: Mapped[str] = mapped_column(String(7), primary_key=True)
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False)
    note: Mapped[str | None] = mapped_column(Text)
    payday: Mapped[int | None] = mapped_column(Integer)
    gross: Mapped[Decimal | None] = mapped_column(Money)
    ni: Mapped[Decimal | None] = mapped_column(Money)
    paye: Mapped[Decimal | None] = mapped_column(Money)
    net: Mapped[Decimal | None] = mapped_column(Money)


class Card(Base):
    """Balance Transfer Cards P3:T7 -- separate from `account`.

    These are balance-transfer cards tracked for payoff, not the credit cards transactions
    are recorded against, so they carry their own opening balance rather than deriving one.
    """

    __tablename__ = "card"

    id: Mapped[int] = mapped_column(primary_key=True)
    uid: Mapped[str] = _uid_column()
    name: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    # 'Amount borrowed' and 'date of borrowing': the transferred balance and when the
    # promotional term starts running.
    opening_balance: Mapped[Decimal] = mapped_column(Money, nullable=False)
    opening_date: Mapped[dt.date] = mapped_column(Date, nullable=False)
    payment_day: Mapped[int | None] = mapped_column(Integer)
    term_months: Mapped[int] = mapped_column(Integer, nullable=False)
    min_payment_pct: Mapped[Decimal] = mapped_column(Money, nullable=False)
    credit_limit: Mapped[Decimal | None] = mapped_column(Money)
    display_order: Mapped[int | None] = mapped_column(Integer)


class CyclingOutgoing(Base):
    """Cycling B3:E -- what the bike costs."""

    __tablename__ = "cycling_outgoing"

    id: Mapped[int] = mapped_column(primary_key=True)
    uid: Mapped[str] = _uid_column()
    date: Mapped[dt.date] = mapped_column(Date, nullable=False, index=True)
    item: Mapped[str | None] = mapped_column(Text)
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False)
    flag: Mapped[str | None] = mapped_column(String(16))  # Commute | General


class CyclingDay(Base):
    """Cycling H3:L -- one row per day ridden.

    The workbook derived the saving with a nested IF in priority order: commute, then band,
    then gym. Stored as flags with the rates in settings, so a fare change does not mean
    editing every historic row.
    """

    __tablename__ = "cycling_day"

    date: Mapped[dt.date] = mapped_column(Date, primary_key=True)
    commute: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    band: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    gym: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)


class CyclingRate(Base):
    """What a day's cycling saves, by kind, effective-dated.

    Was a nested IF inside the Cycling tab's L column -- IF(commute, 10.5, IF(band, 8.9,
    IF(gym, 4.6, 0))) -- so a fare rise meant either rewriting every historic row or
    accepting that old rows now claimed the new fare. Dating the rate fixes both: history
    keeps the fare that applied, and a rise is one new row.
    """

    __tablename__ = "cycling_rate"

    kind: Mapped[str] = mapped_column(String(16), primary_key=True)
    effective_from: Mapped[dt.date] = mapped_column(Date, primary_key=True)
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False)

    __table_args__ = (
        CheckConstraint("kind IN ('commute','band','gym')", name="ck_cycling_rate_kind"),
    )


class CardStatement(Base):
    """Month-tab row 46, 'Credit card bill EoM' -- what the closing statement asks for.

    Only the closing figure is held: the workbook also stored a 'BoM' row, but for two of
    the three cards it is exactly the previous month's closing, so it is derived here. See
    repo.card_outstanding.
    """

    __tablename__ = "card_statement"

    period: Mapped[str] = mapped_column(String(7), primary_key=True)
    account_id: Mapped[int] = mapped_column(ForeignKey("account.id"), primary_key=True)
    bill_eom: Mapped[Decimal] = mapped_column(Money, nullable=False)


class AccountTarget(Base):
    """Summary C23:C26 -- how much a current account should hold in a month.

    The workbook's targets were constants, one of them a formula adding up the standing
    payments it had to cover (`=500+550+350+250*3+100+50+200+300`).
    """

    __tablename__ = "account_target"

    period: Mapped[str] = mapped_column(String(7), primary_key=True)
    account_id: Mapped[int] = mapped_column(ForeignKey("account.id"), primary_key=True)
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False)


class SavingsTarget(Base):
    """Summary columns G and M -- what should be added to savings and to investments.

    A monthly contribution target, not a balance: the 'Required' column accumulates the
    shortfall, so a month that falls short raises the bar for the next one.
    """

    __tablename__ = "savings_target"

    period: Mapped[str] = mapped_column(String(7), primary_key=True)
    savings: Mapped[Decimal | None] = mapped_column(Money)
    investments: Mapped[Decimal | None] = mapped_column(Money)


class Setting(Base):
    """Replaces the Control tab. DeveloperParameters is not carried over -- it only ever
    described sheet geometry."""

    __tablename__ = "setting"

    key: Mapped[str] = mapped_column(String(64), primary_key=True)
    value: Mapped[str] = mapped_column(Text, nullable=False)


class DbMeta(Base):
    """Single-row table carrying the sync revision counter (DESIGN.md 6.3).

    Present from the first migration so the sync work in Phase 2b needs no schema change.
    """

    __tablename__ = "db_meta"

    id: Mapped[int] = mapped_column(primary_key=True, default=1)
    revision: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    base_revision: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    pushed_revision: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    mode: Mapped[str] = mapped_column(String(16), nullable=False, default="online")
    machine: Mapped[str | None] = mapped_column(String(64))
    updated_at: Mapped[dt.datetime] = mapped_column(DateTime, server_default=func.now())

    __table_args__ = (
        CheckConstraint("id = 1", name="ck_db_meta_singleton"),
        CheckConstraint("mode IN ('online','offline','conflict')", name="ck_db_meta_mode"),
    )
