"""SQLAlchemy models.

Phase 0 scope: reference data, the transaction ledger, opening balances and budgets --
everything the reconciliation gate needs. The feature-module tables (projection, payslip,
card, cycling) arrive with their phases; adding tables to SQLite later is free, it is
altering existing ones that hurts.

Money is stored as INTEGER pence via the Money type below. SQLite has no decimal type, so
a REAL column would reintroduce exactly the float artefacts the workbook already suffers
from (1530.0000000000146). Integers keep SUM() exact, which matters because every balance
in this application is a sum.
"""

from __future__ import annotations

import datetime as dt
from decimal import Decimal, ROUND_HALF_UP

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    TypeDecorator,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

PENCE = Decimal("0.01")


class Money(TypeDecorator):
    """Decimal pounds in Python, integer pence in the database."""

    impl = Integer
    cache_ok = True

    def process_bind_param(self, value, dialect):
        if value is None:
            return None
        return int(Decimal(str(value)).quantize(PENCE, rounding=ROUND_HALF_UP) * 100)

    def process_result_value(self, value, dialect):
        if value is None:
            return None
        return (Decimal(value) / 100).quantize(PENCE)


class Base(DeclarativeBase):
    pass


# A random 16-byte hex string, generated by SQLite so it applies to rows inserted by any
# route. This is the sync identity for cross-machine merges (DESIGN.md 6.3.3); the integer
# primary key stays for joins and readability.
_UID_DEFAULT = text("lower(hex(randomblob(16)))")


def _uid_column() -> Mapped[str]:
    return mapped_column(String(32), unique=True, nullable=False, server_default=_UID_DEFAULT)


# --------------------------------------------------------------------------- reference


class Account(Base):
    __tablename__ = "account"

    id: Mapped[int] = mapped_column(primary_key=True)
    uid: Mapped[str] = _uid_column()
    name: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    short_code: Mapped[str] = mapped_column(String(16), unique=True, nullable=False)
    # 'bank' or 'credit_card'. Determines posting sign: a credit card balance is positive
    # debt, so a debit increases it. Derived from the month-tab row-4 formula on import.
    type: Mapped[str] = mapped_column(String(16), nullable=False)

    is_savings: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    savings_limit: Mapped[Decimal | None] = mapped_column(Money)
    is_investment: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    investment_limit: Mapped[Decimal | None] = mapped_column(Money)
    # What this pot had already been credited towards its target before the record here
    # begins. The cumulative target starts from this rather than from zero, so 'required'
    # compares like with like: without it a running total of contributions that starts at
    # nothing is measured against a balance built up over years, and every month reads as
    # thousands ahead of target.
    savings_seed: Mapped[Decimal | None] = mapped_column(Money)
    is_isa: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    # Earmarked pots -- money that is nominally saved but already spoken for. The Summary
    # tab's 'Less SC & Wed' column subtracted these by hand; flagging the accounts means the
    # column follows when a pot is added, which the workbook's header did not (Tembo joined
    # in June and the label was never updated).
    exclude_from_savings: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False
    )
    # Whether interest arrives already taxed. The interest tracker held this as a per-account
    # 'Gross'/'Net' row and used it to decide whether tax paid should be deducted again --
    # `IF(D3="Net", D4-D5, D4)`. Everything is gross bar Halifax, so False is the default and
    # the flag names the exception rather than the rule.
    interest_net: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    # Credit cards only: the day the statement is issued and the day the direct debit is
    # taken. Month-tab rows 48 and 50, which held them per month even though they never
    # varied by month.
    statement_day: Mapped[int | None] = mapped_column(Integer)
    payment_day: Mapped[int | None] = mapped_column(Integer)

    # The day the account's funding cycle begins -- payday for the account that receives the
    # salary, the 1st for one topped up at the start of the month. Commitments are ordered
    # and counted down from it, so an account funded on the 19th shows the 19th to the 18th
    # rather than a calendar month, which is the window its balance actually has to cover.
    # Null means the 1st.
    commitment_start_day: Mapped[int | None] = mapped_column(Integer)

    display_order: Mapped[int | None] = mapped_column(Integer)
    # Effective dating replaces the twelve per-month offset columns in Selections!Z:AK and
    # removes the need for update_months entirely (DESIGN.md 3.2).
    valid_from: Mapped[dt.date] = mapped_column(Date, nullable=False)
    valid_to: Mapped[dt.date | None] = mapped_column(Date)

    __table_args__ = (
        CheckConstraint("type IN ('bank','credit_card')", name="ck_account_type"),
    )

    def __repr__(self) -> str:
        return f"<Account {self.name!r} {self.type}>"


class Classification(Base):
    """Bills, Food, Excess, Savings ... -- the workbook's 'Purchase type'."""

    __tablename__ = "classification"

    id: Mapped[int] = mapped_column(primary_key=True)
    uid: Mapped[str] = _uid_column()
    name: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    legacy_ref: Mapped[int] = mapped_column(Integer, nullable=False)  # Selections!I
    direction: Mapped[int] = mapped_column(Integer, nullable=False)  # Selections!J, +1/-1
    rollover: Mapped[str] = mapped_column(String(16), nullable=False, default="none")
    counts_as_spend: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    display_order: Mapped[int | None] = mapped_column(Integer)
    valid_from: Mapped[dt.date] = mapped_column(Date, nullable=False)
    valid_to: Mapped[dt.date | None] = mapped_column(Date)

    # 'credit' / 'debit' rather than the workbook's 'positive' / 'negative': the rule is
    # about which kind of balance carries forward, which is clearer said that way round.
    __table_args__ = (
        CheckConstraint(
            "rollover IN ('none','all','credit','debit')", name="ck_classification_rollover"
        ),
    )

    def __repr__(self) -> str:
        return f"<Classification {self.name!r}>"


class Category(Base):
    """Mortgage, Going Out, Electricity ... -- the workbook's 'Category'."""

    __tablename__ = "category"

    id: Mapped[int] = mapped_column(primary_key=True)
    uid: Mapped[str] = _uid_column()
    name: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    grouping: Mapped[str] = mapped_column(String(32), nullable=False)  # Selections!AM
    spend_type: Mapped[str] = mapped_column(String(16), nullable=False)  # Selections!AO
    display_order: Mapped[int | None] = mapped_column(Integer)
    valid_from: Mapped[dt.date] = mapped_column(Date, nullable=False)
    valid_to: Mapped[dt.date | None] = mapped_column(Date)

    __table_args__ = (
        CheckConstraint("spend_type IN ('Credit','Debit','All')", name="ck_category_spend_type"),
    )

    def __repr__(self) -> str:
        return f"<Category {self.name!r}>"


# ------------------------------------------------------------------------------ ledger


class ImportBatch(Base):
    __tablename__ = "import_batch"

    id: Mapped[int] = mapped_column(primary_key=True)
    uid: Mapped[str] = _uid_column()
    created_at: Mapped[dt.datetime] = mapped_column(DateTime, server_default=func.now())
    filename: Mapped[str | None] = mapped_column(Text)
    row_count: Mapped[int | None] = mapped_column(Integer)
    note: Mapped[str | None] = mapped_column(Text)

    transactions: Mapped[list["Txn"]] = relationship(back_populates="batch")


class Txn(Base):
    """One user-entered transaction. Transfers are a single row with both accounts set;
    postings() explodes them into signed per-account movements."""

    __tablename__ = "txn"

    id: Mapped[int] = mapped_column(primary_key=True)
    uid: Mapped[str] = _uid_column()

    txn_date: Mapped[dt.date] = mapped_column(Date, nullable=False, index=True)
    period: Mapped[str] = mapped_column(String(7), nullable=False, index=True)  # 'YYYY-MM'
    type: Mapped[str] = mapped_column(String(16), nullable=False)
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False)

    account_from_id: Mapped[int] = mapped_column(ForeignKey("account.id"), nullable=False)
    account_to_id: Mapped[int | None] = mapped_column(ForeignKey("account.id"))
    category_id: Mapped[int | None] = mapped_column(ForeignKey("category.id"))
    classification_id: Mapped[int | None] = mapped_column(ForeignKey("classification.id"))

    comment: Mapped[str | None] = mapped_column(Text)
    category_comment: Mapped[str | None] = mapped_column(Text)
    # Charitable giving, tracked for its own sake rather than as a spending category: the
    # interest tracker kept a separate sheet for it because the figure wanted is the year's
    # total given, which no category could produce -- a donation and its transaction fee are
    # one payment out of the account but only one of them is a donation.
    is_donation: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    # The workbook's natural key (e.g. '0401_BAAM_0'). Useful for de-duplicating re-imports
    # and for flagging near-duplicates during a cross-machine merge (DESIGN.md 6.3.4).
    legacy_identifier: Mapped[str | None] = mapped_column(String(64), index=True)

    created_at: Mapped[dt.datetime] = mapped_column(DateTime, server_default=func.now())
    deleted_at: Mapped[dt.datetime | None] = mapped_column(DateTime)
    deleted_reason: Mapped[str | None] = mapped_column(Text)
    source: Mapped[str] = mapped_column(String(16), nullable=False, default="manual")
    batch_id: Mapped[int | None] = mapped_column(ForeignKey("import_batch.id"))

    batch: Mapped[ImportBatch | None] = relationship(back_populates="transactions")
    account_from: Mapped[Account] = relationship(foreign_keys=[account_from_id])
    account_to: Mapped[Account | None] = relationship(foreign_keys=[account_to_id])
    category: Mapped[Category | None] = relationship()
    classification: Mapped[Classification | None] = relationship()

    __table_args__ = (
        CheckConstraint("type IN ('Credit','Debit','Transfer')", name="ck_txn_type"),
        CheckConstraint("amount >= 0", name="ck_txn_amount_non_negative"),
        # A transfer needs a destination; anything else must not have one.
        CheckConstraint(
            "(type = 'Transfer') = (account_to_id IS NOT NULL)", name="ck_txn_transfer_has_to"
        ),
    )

    def __repr__(self) -> str:
        return f"<Txn {self.txn_date} {self.type} {self.amount}>"


# ------------------------------------------------------------------- periodic reference


class OpeningBalance(Base):
    """Month-tab row 60 ('Start') per account."""

    __tablename__ = "opening_balance"

    account_id: Mapped[int] = mapped_column(ForeignKey("account.id"), primary_key=True)
    period: Mapped[str] = mapped_column(String(7), primary_key=True)
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False)


class Budget(Base):
    """Month-tab columns C and D: Income and Expected Costs, per category."""

    __tablename__ = "budget"

    period: Mapped[str] = mapped_column(String(7), primary_key=True)
    category_id: Mapped[int] = mapped_column(ForeignKey("category.id"), primary_key=True)
    income: Mapped[Decimal | None] = mapped_column(Money)
    expected: Mapped[Decimal | None] = mapped_column(Money)


class Projection(Base):
    """Projected Costs E8:K39 -- expected spend per day, per classification.

    The workbook held one month at a time and the month tabs read it through xlProj<Class>
    for any date after today. Keyed by date here, so several months can coexist.
    """

    __tablename__ = "projection"

    proj_date: Mapped[dt.date] = mapped_column(Date, primary_key=True)
    classification_id: Mapped[int] = mapped_column(
        ForeignKey("classification.id"), primary_key=True
    )
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False, default=Decimal("0"))
    comment: Mapped[str | None] = mapped_column(Text)


class ClassificationOpening(Base):
    """Opening balance for a classification's running total.

    April's Running Excess formula ends in a bare '-2632.45' -- the balance carried in from
    the previous year's workbook, typed into the formula because there was nowhere to store
    it. Here it has a home, so the year can start from a stated figure rather than a
    literal buried in a cell.
    """

    __tablename__ = "classification_opening"

    period: Mapped[str] = mapped_column(String(7), primary_key=True)
    classification_id: Mapped[int] = mapped_column(
        ForeignKey("classification.id"), primary_key=True
    )
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False)


class ClassificationAllowance(Base):
    """Month-tab C54, 'Spend per day'.

    Running Excess gains this every day of the month, on top of actual spend. The workbook
    applied it by testing whether the column header ended in 'Excess'; keying it properly
    means any classification can carry an allowance, and it can differ by month -- which it
    does, being absent before July and 30 from July onwards.
    """

    __tablename__ = "classification_allowance"

    period: Mapped[str] = mapped_column(String(7), primary_key=True)
    classification_id: Mapped[int] = mapped_column(
        ForeignKey("classification.id"), primary_key=True
    )
    daily_amount: Mapped[Decimal] = mapped_column(Money, nullable=False)


class Payslip(Base):
    """Salary tracker, actual side (columns B:M)."""

    __tablename__ = "payslip"

    period: Mapped[str] = mapped_column(String(7), primary_key=True)
    payday: Mapped[int | None] = mapped_column(Integer)
    gross: Mapped[Decimal | None] = mapped_column(Money)
    ni: Mapped[Decimal | None] = mapped_column(Money)
    holiday_pay: Mapped[Decimal | None] = mapped_column(Money)
    cycle_to_work: Mapped[Decimal | None] = mapped_column(Money)
    # The car allowance as the payslip states it, separately from gross. It is taxable but
    # not pensionable, so lumping it into gross charges the pension against it -- which is
    # why the expected side has always kept the two apart. This lets the actual side match.
    car_allowance: Mapped[Decimal | None] = mapped_column(Money)
    paye: Mapped[Decimal | None] = mapped_column(Money)
    net: Mapped[Decimal | None] = mapped_column(Money)
    # Expected side (columns O:W): the inputs the model needs, not its outputs.
    salary: Mapped[Decimal | None] = mapped_column(Money)  # O, annual
    # P, and *not* salary/12: a bonus month carries its own figure, which is why May's
    # expected gross is 39,724 against an annual salary of 128,350.
    expected_gross: Mapped[Decimal | None] = mapped_column(Money)
    benefits: Mapped[Decimal | None] = mapped_column(Money)
    additional: Mapped[Decimal | None] = mapped_column(Money)


class SalaryAssumption(Base):
    """The PAYE/NI bands from Salary tracker C18:F36, as monthly figures.

    Effective-dated because the personal allowance is tapered in four steps across the year
    (PA - 1 through PA - 4, each with its own start date in F24:F27).

    Rates are stored as percentages, not fractions: 8% is 8.00, not 0.08. The Money column
    holds two decimal places, so a fraction could only express whole percentage points --
    fine for 20% and 45%, useless for an 8.5% NI rate. As percentages the same column
    resolves to a hundredth of a point.
    """

    __tablename__ = "salary_assumption"

    tax_year: Mapped[int] = mapped_column(Integer, primary_key=True)
    key: Mapped[str] = mapped_column(String(48), primary_key=True)
    effective_from: Mapped[dt.date] = mapped_column(Date, primary_key=True)
    value: Mapped[Decimal] = mapped_column(Money, nullable=False)


class SalaryProfile(Base):
    """Annual salary, effective-dated -- the input behind 'Gross pay (expected)'.

    The workbook typed the annual figure into every one of the twelve rows of column O, so a
    pay rise meant editing each month from that point on and hoping none were missed. One
    row per change here; the month picks up whichever is in force.
    """

    __tablename__ = "salary_profile"

    id: Mapped[int] = mapped_column(primary_key=True)
    uid: Mapped[str] = _uid_column()
    effective_from: Mapped[dt.date] = mapped_column(Date, unique=True, nullable=False)
    # The input. The car allowance is a function of it (12% of the first 50,000 plus 5%
    # above, all parameterised), so storing the total as well would let the two drift the
    # moment either was edited -- the same reasoning as the basic rate band.
    base_salary: Mapped[Decimal | None] = mapped_column(Money)
    # What used to be stored: base *plus* car allowance, which is why 128,350.25 could not be
    # reconciled against a payslip showing a base of 118,905. Retained as the pre-split
    # record and no longer read; repo.salary_in_force works from base_salary.
    annual_salary: Mapped[Decimal] = mapped_column(Money, nullable=False)
    note: Mapped[str | None] = mapped_column(Text)


class Bonus(Base):
    """A one-off payment on top of salary/12, by the month it is paid.

    May's expected gross was `ROUND(O5/12,2)+29028.48` -- the bonus welded into the formula,
    which is why expected gross could not simply be derived. Held as data, the derivation
    works again: expected gross = salary in force / 12 + any bonus for the month.

    The actual columns are here rather than on `payslip` because a bonus is frequently paid
    on its own day, as its own payment with its own deductions. `payslip` is keyed by period,
    so recording the bonus there would have overwritten the month's salary -- two payments in
    one month is exactly the case a single row per month cannot hold. The Salary page adds
    the two together.
    """

    __tablename__ = "bonus"

    period: Mapped[str] = mapped_column(String(7), primary_key=True)
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False)
    note: Mapped[str | None] = mapped_column(Text)
    payday: Mapped[int | None] = mapped_column(Integer)
    gross: Mapped[Decimal | None] = mapped_column(Money)
    ni: Mapped[Decimal | None] = mapped_column(Money)
    paye: Mapped[Decimal | None] = mapped_column(Money)
    net: Mapped[Decimal | None] = mapped_column(Money)


class Card(Base):
    """Balance Transfer Cards P3:T7 -- separate from `account`.

    These are balance-transfer cards tracked for payoff, not the credit cards transactions
    are recorded against, so they carry their own opening balance rather than deriving one.
    """

    __tablename__ = "card"

    id: Mapped[int] = mapped_column(primary_key=True)
    uid: Mapped[str] = _uid_column()
    name: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    # 'Amount borrowed' and 'date of borrowing': the transferred balance and when the
    # promotional term starts running.
    opening_balance: Mapped[Decimal] = mapped_column(Money, nullable=False)
    opening_date: Mapped[dt.date] = mapped_column(Date, nullable=False)
    payment_day: Mapped[int | None] = mapped_column(Integer)
    term_months: Mapped[int] = mapped_column(Integer, nullable=False)
    # A percentage, not a fraction: 2.5, not 0.025. As a fraction in a Money column it
    # could only ever be a whole percentage point, so every card at 2.5% was stored --
    # and charged -- at 3%. Same reasoning as SalaryAssumption above.
    min_payment_pct: Mapped[Decimal] = mapped_column(Money, nullable=False)
    credit_limit: Mapped[Decimal | None] = mapped_column(Money)
    display_order: Mapped[int | None] = mapped_column(Integer)


class CyclingOutgoing(Base):
    """Cycling B3:E -- what the bike costs."""

    __tablename__ = "cycling_outgoing"

    id: Mapped[int] = mapped_column(primary_key=True)
    uid: Mapped[str] = _uid_column()
    date: Mapped[dt.date] = mapped_column(Date, nullable=False, index=True)
    item: Mapped[str | None] = mapped_column(Text)
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False)
    flag: Mapped[str | None] = mapped_column(String(16))  # Commute | General


class CyclingDay(Base):
    """Cycling H3:L -- one row per day ridden.

    The workbook derived the saving with a nested IF in priority order: commute, then band,
    then gym. Stored as flags with the rates in settings, so a fare change does not mean
    editing every historic row.
    """

    __tablename__ = "cycling_day"

    date: Mapped[dt.date] = mapped_column(Date, primary_key=True)
    commute: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    band: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    gym: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)


class CyclingRate(Base):
    """What a day's cycling saves, by kind, effective-dated.

    Was a nested IF inside the Cycling tab's L column -- IF(commute, 10.5, IF(band, 8.9,
    IF(gym, 4.6, 0))) -- so a fare rise meant either rewriting every historic row or
    accepting that old rows now claimed the new fare. Dating the rate fixes both: history
    keeps the fare that applied, and a rise is one new row.
    """

    __tablename__ = "cycling_rate"

    kind: Mapped[str] = mapped_column(String(16), primary_key=True)
    effective_from: Mapped[dt.date] = mapped_column(Date, primary_key=True)
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False)

    __table_args__ = (
        CheckConstraint("kind IN ('commute','band','gym')", name="ck_cycling_rate_kind"),
    )


class CardStatement(Base):
    """Month-tab row 46, 'Credit card bill EoM' -- what the closing statement asks for.

    Only the closing figure is held: the workbook also stored a 'BoM' row, but for two of
    the three cards it is exactly the previous month's closing, so it is derived here. See
    repo.card_outstanding.
    """

    __tablename__ = "card_statement"

    period: Mapped[str] = mapped_column(String(7), primary_key=True)
    account_id: Mapped[int] = mapped_column(ForeignKey("account.id"), primary_key=True)
    bill_eom: Mapped[Decimal] = mapped_column(Money, nullable=False)


class AccountTarget(Base):
    """Summary C23:C26 -- how much a current account should hold in a month.

    The workbook's targets were constants, one of them a formula adding up the standing
    payments it had to cover (`=500+550+350+250*3+100+50+200+300`).
    """

    __tablename__ = "account_target"

    period: Mapped[str] = mapped_column(String(7), primary_key=True)
    account_id: Mapped[int] = mapped_column(ForeignKey("account.id"), primary_key=True)
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False)


class AccountCommitment(Base):
    """One payment an account has to cover, and the day of the month it goes.

    An AccountTarget is a single number for the month, which cannot say *when* the money is
    needed -- and that is usually the question. £2,642.85 of a First Direct target leaves on
    the 1st, so a balance that would comfortably cover the month is still short on the day
    that matters. These are the parts that make the total up, each with its own day.

    Deliberately not effective-dated, unlike SavingsPlan or the tax bands. Those are read
    against a month that has already happened, so an old figure still has to be recoverable.
    This list describes what is due *now*: nothing derived from it is stored, no historical
    figure moves when it changes, and amending a row is the intended way to record that the
    gym went up. Keeping revisions would be a history with no reader.

    `day` is a day of the month rather than a date, since these repeat. A 31 lands on the
    30th in April and the 28th in February -- see repo._clamp_day.

    An amount of zero means 'due, amount not known yet' rather than 'nothing is due': the row
    is worth keeping for its date alone, and the Summary page flags it rather than showing a
    confident £0.00.
    """

    __tablename__ = "account_commitment"

    id: Mapped[int] = mapped_column(primary_key=True)
    account_id: Mapped[int] = mapped_column(ForeignKey("account.id"), nullable=False)
    name: Mapped[str] = mapped_column(String(80), nullable=False)
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False)
    day: Mapped[int] = mapped_column(Integer, nullable=False)

    account: Mapped[Account] = relationship()

    # Per account, not globally: 'Lottery' is a real commitment on two different accounts,
    # and so is a transfer named after the account it goes to.
    __table_args__ = (
        UniqueConstraint("account_id", "name", name="uq_account_commitment_name"),
    )


class SavingsTarget(Base):
    """Summary columns G and M -- what should be added to savings and to investments.

    A monthly contribution target, not a balance: the 'Required' column accumulates the
    shortfall, so a month that falls short raises the bar for the next one.

    Superseded by SavingsPlan, which holds the same thing per account. Retained as the
    pre-split record and no longer read, the same way `salary_profile.annual_salary` is.
    """

    __tablename__ = "savings_target"

    period: Mapped[str] = mapped_column(String(7), primary_key=True)
    savings: Mapped[Decimal | None] = mapped_column(Money)
    investments: Mapped[Decimal | None] = mapped_column(Money)


class SavingsPlan(Base):
    """The interest tracker's 'Savings & investment plan' B5:H9 -- a monthly contribution
    target per account, effective-dated.

    The workbook held one column per revision of the plan (`Target - 08/25`, `Target - 10/25`
    ...) with the date in the row above, so reading it meant knowing which column was current.
    Here each figure carries its own start date and the set in force on a month is the one
    that applies, which is the same shape as the tax bands.

    Per account rather than two lump sums, because the lump sums were only ever the totals:
    250 + 350 + 300 into NS&I, Wedding and Marcus is the 900 the dashboard had, and 250 + 100
    into the two investment accounts is its 350. Splitting them means a shortfall can be read
    back to the pot that caused it, and the overview is derived rather than typed twice.
    """

    __tablename__ = "savings_plan"

    id: Mapped[int] = mapped_column(primary_key=True)
    account_id: Mapped[int] = mapped_column(ForeignKey("account.id"), nullable=False)
    effective_from: Mapped[dt.date] = mapped_column(Date, nullable=False)
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False)

    account: Mapped[Account] = relationship()

    __table_args__ = (
        UniqueConstraint("account_id", "effective_from", name="uq_savings_plan_account_date"),
    )


class SavingsAdjustment(Base):
    """A one-off planned addition to, or withdrawal from, a pot in a single month.

    The plan is a standing figure that repeats until it is revised. This is the other kind:
    a lump sum going in, or coming out, in one named month and not again. Folding it into
    the plan would misstate every month after it, and leaving it out means the target is
    knowingly wrong for the month it lands in.

    Signed, so a withdrawal is negative. Several are allowed in a month -- each carries its
    own note, which is the only way to tell two of them apart afterwards.
    """

    __tablename__ = "savings_adjustment"

    id: Mapped[int] = mapped_column(primary_key=True)
    period: Mapped[str] = mapped_column(String(7), nullable=False, index=True)
    account_id: Mapped[int] = mapped_column(ForeignKey("account.id"), nullable=False)
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False)
    note: Mapped[str | None] = mapped_column(Text)

    account: Mapped[Account] = relationship()


class ImportRule(Base):
    """A description a bank uses for a movement between two of your own accounts.

    A bank export describes only its own side: HSBC records paying the Amex bill as
    'AMERICAN EXPRESS DD' and a debit, and says nothing about which card received it. When
    both files are imported together the two halves can be matched on date and amount, which
    needs no configuration and is the stronger signal. This is for the rest -- an account
    that is not being imported, or a movement whose other half falls outside the window.

    `pattern` is matched as a case-insensitive substring of the description, so 'HSBC CARD
    PYMT' catches the reference numbers that follow it. Deliberately not a regular
    expression: these are typed in by hand, and a bad regex fails at import time on a page
    that is otherwise about money.

    A rule only ever *proposes*, and only ever names an account of your own. A movement whose
    far side belongs to somebody else needs no rule: with nothing to match it against it is
    recorded as the plain debit or credit the bank called it.

    Everything a rule fills in lands in the import grid for review, and nothing here can
    write to the ledger.
    """

    __tablename__ = "import_rule"

    id: Mapped[int] = mapped_column(primary_key=True)
    pattern: Mapped[str] = mapped_column(String(120), nullable=False)
    # The account on the other side. Which of the two is 'from' comes from the direction of
    # the row being matched, not from here.
    account_id: Mapped[int] = mapped_column(ForeignKey("account.id"), nullable=False)
    note: Mapped[str | None] = mapped_column(Text)

    account: Mapped[Account] = relationship()

    __table_args__ = (
        UniqueConstraint("pattern", name="uq_import_rule_pattern"),
    )


class PensionPot(Base):
    """One pension arrangement -- a provider holding a pot.

    Effective-dated like `account`, and for the same two reasons: a pot joined part way
    through (Aegon opened with nothing in it in November 2023) and a pot can be transferred
    out. `valid_to` stops the last known value being carried forward for ever, which is what
    would otherwise happen -- a valuation is a point in time, and nothing in the data says a
    pot has stopped existing except the absence of new ones, which is indistinguishable from
    not having got round to it.
    """

    __tablename__ = "pension_pot"

    id: Mapped[int] = mapped_column(primary_key=True)
    uid: Mapped[str] = _uid_column()
    name: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    display_order: Mapped[int | None] = mapped_column(Integer)
    valid_from: Mapped[dt.date] = mapped_column(Date, nullable=False)
    valid_to: Mapped[dt.date | None] = mapped_column(Date)
    note: Mapped[str | None] = mapped_column(Text)

    def __repr__(self) -> str:
        return f"<PensionPot {self.name!r}>"


class PensionValuation(Base):
    """What a pot was worth on a day the statement was read.

    One row per pot per date rather than one row per date holding every pot, because the
    providers do not publish on the same day and a row that demands all three forces either a
    stale figure or a gap. The reader carries the most recent figure forward per pot and says
    where it did so -- see repo.pension_history.
    """

    __tablename__ = "pension_valuation"

    pot_id: Mapped[int] = mapped_column(ForeignKey("pension_pot.id"), primary_key=True)
    on_date: Mapped[dt.date] = mapped_column(Date, primary_key=True)
    value: Mapped[Decimal] = mapped_column(Money, nullable=False)

    pot: Mapped[PensionPot] = relationship()


class PensionContribution(Base):
    """A movement of cash into or out of a pot, apart from investment growth.

    This is what makes a return calculable. Without it a pot being paid into cannot be told
    apart from one that grew: the balance rises either way, and dividing this month's value by
    last month's reports every contribution as a gain. Held signed -- money in is positive, a
    charge is negative -- rather than as a credit column and a debit column, because every
    calculation wants the net and the pair only ever produced one of the two.

    `kind` is for reporting, never for arithmetic: 'what have the charges cost' is a question
    the ledger can answer and the return maths does not care about, which sees only the net.
    """

    __tablename__ = "pension_contribution"

    id: Mapped[int] = mapped_column(primary_key=True)
    uid: Mapped[str] = _uid_column()
    pot_id: Mapped[int] = mapped_column(ForeignKey("pension_pot.id"), nullable=False, index=True)
    on_date: Mapped[dt.date] = mapped_column(Date, nullable=False, index=True)
    amount: Mapped[Decimal] = mapped_column(Money, nullable=False)
    kind: Mapped[str] = mapped_column(String(16), nullable=False, default="contribution")
    note: Mapped[str | None] = mapped_column(Text)

    pot: Mapped[PensionPot] = relationship()

    __table_args__ = (
        CheckConstraint(
            "kind IN ('contribution','charge','interest','other')",
            name="ck_pension_contribution_kind",
        ),
    )


class Setting(Base):
    """Replaces the Control tab. DeveloperParameters is not carried over -- it only ever
    described sheet geometry."""

    __tablename__ = "setting"

    key: Mapped[str] = mapped_column(String(64), primary_key=True)
    value: Mapped[str] = mapped_column(Text, nullable=False)


class DbMeta(Base):
    """Single-row table carrying the sync revision counter (DESIGN.md 6.3).

    Present from the first migration so the sync work in Phase 2b needs no schema change.
    """

    __tablename__ = "db_meta"

    id: Mapped[int] = mapped_column(primary_key=True, default=1)
    revision: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    base_revision: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    pushed_revision: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    mode: Mapped[str] = mapped_column(String(16), nullable=False, default="online")
    machine: Mapped[str | None] = mapped_column(String(64))
    updated_at: Mapped[dt.datetime] = mapped_column(DateTime, server_default=func.now())

    __table_args__ = (
        CheckConstraint("id = 1", name="ck_db_meta_singleton"),
        CheckConstraint("mode IN ('online','offline','conflict')", name="ck_db_meta_mode"),
    )
